version: "3.9"
services:
  mongodb:
    environment:
      MONGO_INITDB_DATABASE: django
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    hostname: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data-mongodb:/data/db

  api:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/blog_django
    ports:
      - "8000:8000"
    depends_on:
      - mongodb